# Generated by Django 2.1.5 on 2019-03-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kaiin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会員名')),
                ('login_pass', models.CharField(max_length=255, verbose_name='ログインPass')),
            ],
            options={
                'db_table': 'kaiin',
            },
        ),
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='問題タイトル')),
                ('prob_bun', models.CharField(max_length=255, verbose_name='問題文')),
                ('sentaku_1', models.CharField(max_length=255, verbose_name='選択肢１')),
                ('sentaku_2', models.CharField(max_length=255, verbose_name='選択肢２')),
                ('sentaku_3', models.CharField(max_length=255, verbose_name='選択肢３')),
                ('sentaku_4', models.CharField(max_length=255, verbose_name='選択肢４')),
                ('seikai', models.IntegerField(verbose_name='正解番号')),
                ('kaisetsu', models.CharField(max_length=5000, verbose_name='解説')),
            ],
            options={
                'db_table': 'prob',
            },
        ),
        migrations.CreateModel(
            name='Shintyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seogo', models.IntegerField(verbose_name='正誤')),
                ('answer_date', models.DateField(verbose_name='最終回答日')),
                ('kaiin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Kaiin')),
                ('prob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Prob')),
            ],
            options={
                'db_table': 'shintyoku',
            },
        ),
        migrations.CreateModel(
            name='Shou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shou_name', models.CharField(max_length=255, verbose_name='章名')),
            ],
            options={
                'db_table': 'shou',
            },
        ),
        migrations.AddField(
            model_name='shintyoku',
            name='shou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Shou'),
        ),
        migrations.AddField(
            model_name='prob',
            name='shou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Shou'),
        ),
    ]
