# Generated by Django 2.1.5 on 2019-03-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shintyoku',
            old_name='seogo',
            new_name='seigo',
        ),
    ]
