# Generated by Django 2.1.5 on 2019-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190310_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='prob_bun',
            field=models.CharField(max_length=5000, verbose_name='問題文'),
        ),
    ]
