# Generated by Django 2.1.5 on 2019-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='seigo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正誤'),
        ),
    ]
