# Generated by Django 2.1.5 on 2019-03-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190312_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='prob',
            name='prob_num',
            field=models.IntegerField(default=1, verbose_name='問題番号'),
            preserve_default=False,
        ),
    ]
