# Generated by Django 2.1.5 on 2019-03-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_prob_prob_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='shou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Shou', verbose_name='章番号'),
        ),
        migrations.AlterField(
            model_name='shintyoku',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Prob'),
        ),
    ]
