# Generated by Django 2.1.5 on 2019-03-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190318_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='kaiin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
