# Generated by Django 2.1.5 on 2019-03-19 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190319_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='kaiin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shintyoku',
            name='shou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Shou'),
        ),
    ]
