# Generated by Django 2.1.5 on 2019-03-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20190319_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='shou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Shou', verbose_name='章番号'),
        ),
    ]
