# Generated by Django 2.1.5 on 2019-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20190320_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='seigo',
            field=models.CharField(default=11, max_length=255, verbose_name='正誤'),
            preserve_default=False,
        ),
    ]
