# Generated by Django 2.1.5 on 2019-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20190322_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='seigo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正誤'),
        ),
    ]
