# Generated by Django 2.1.5 on 2019-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190322_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='answer_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='最終回答日'),
        ),
    ]
