# Generated by Django 2.1.5 on 2019-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20190322_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shintyoku',
            name='seigo',
        ),
        migrations.AlterField(
            model_name='kaiin',
            name='login_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ログインPass'),
        ),
        migrations.AlterField(
            model_name='kaiin',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='会員名'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='kaisetsu',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='prob_bun',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='問題文'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='seikai',
            field=models.IntegerField(blank=True, null=True, verbose_name='正解番号'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='sentaku_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選択肢１'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='sentaku_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選択肢２'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='sentaku_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選択肢３'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='sentaku_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選択肢４'),
        ),
        migrations.AlterField(
            model_name='prob',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='問題タイトル'),
        ),
        migrations.AlterField(
            model_name='shintyoku',
            name='answer_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終回答日'),
        ),
        migrations.AlterField(
            model_name='shou',
            name='shou_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='章名'),
        ),
    ]
