# Generated by Django 2.1.5 on 2019-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20190322_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='prob_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='問題番号'),
        ),
        migrations.AlterModelTable(
            name='kaiin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prob',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shintyoku',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shou',
            table=None,
        ),
    ]
