# Generated by Django 2.1.5 on 2019-03-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20190322_2346'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kaiin',
            table='kaiin',
        ),
        migrations.AlterModelTable(
            name='prob',
            table='prob',
        ),
        migrations.AlterModelTable(
            name='shintyoku',
            table='shintyoku',
        ),
        migrations.AlterModelTable(
            name='shou',
            table='shou',
        ),
    ]
