# Generated by Django 2.1.5 on 2019-03-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20190322_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='shintyoku',
            name='seigo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正誤'),
        ),
    ]
