# Generated by Django 2.1.5 on 2019-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_shintyoku_seigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shintyoku',
            name='seigo',
            field=models.CharField(default=1, max_length=255, verbose_name='正誤'),
            preserve_default=False,
        ),
    ]
