# Generated by Django 2.1.5 on 2019-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth',
            field=models.IntegerField(default=1, verbose_name='権限'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corp',
            field=models.CharField(default=1, max_length=255, verbose_name='企業名'),
            preserve_default=False,
        ),
    ]
