# Generated by Django 2.1.5 on 2019-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190319_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth',
            field=models.IntegerField(blank=True, null=True, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='企業名'),
        ),
    ]
