# Generated by Django 2.1.5 on 2019-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190319_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_edit',
            field=models.IntegerField(blank=True, null=True, verbose_name='編集権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_view',
            field=models.IntegerField(blank=True, null=True, verbose_name='結果確認権限'),
        ),
    ]
