# Generated by Django 2.1.5 on 2019-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190319_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_view',
            field=models.IntegerField(blank=True, null=True, verbose_name='確認権限'),
        ),
    ]
