# Generated by Django 2.1.5 on 2019-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190320_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_edit',
            field=models.IntegerField(default=11, verbose_name='編集権限'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_view',
            field=models.IntegerField(default=11, verbose_name='確認権限'),
            preserve_default=False,
        ),
    ]
