# Generated by Django 2.1.5 on 2019-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190322_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='corp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='企業ID'),
        ),
    ]
